app:
  jwt:
    secret: DaeguGreenArtAcademyClass502ForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000


file:
  dir: D:/download/greengram4/



spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram4
    username: root
    password: green502




mybatis:
  mapper-locations: mappers/**/*.xml
springdoc:
  swagger-ui:
    path: /swagger.html

fcm:
  certification: serviceAccountKey.json

