openapi:
  apartment:
    base-url: http://openapi.molit.go.kr
    data-url: OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: Y2UOCkD8Ilv2gViPGV33ddNTTQfRi92i8mRzUeQX%2BNgSiNTO3gp9hJZX4J6u8uXucMM6RdRBoGxMn6XHfsEzNA%3D%3D


app:
  jwt:
    secret: DaeguGreenArtAcademyClass502ForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 129600000


file:
  dir: D:/download/greengram4/



spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram4
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy



#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/preschool
#    username: root
#    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml
springdoc:
  swagger-ui:
    path: /swagger.html

fcm:
  certification: serviceAccountKey.json



logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

---


spring:
  config:
    activate:
      on-profile: "prod1"
  datasource:
    url: jdbc.mariadb://192.168.0.144:55/greengram3
    password: greendev1


file:
  dir: /home/download/
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: "prod2"
server:
  port: 8082